
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2

  redis:
    host: localhost
    port: 6379

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      show-sql: true
      format_sql: true



