
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: username
    password: password
    driver-class-name: org.postgresql.Driver

  redis:
    host: localhost
    port: 6379

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      show-sql: true
      format_sql: true
    open-in-view: false