version: "3"

services:
  redis:
    container_name: redis
    image: redis:latest
    restart: always
    hostname: redis
    network_mode: host
    ports:
      - "6379:6379"
    volumes:
      - ./redis/conf:/etc/redis